config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'blog#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog
  attr_writer :post_source, :entries

  def initialize
    @entries = []
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint & opinion"
  end

  def new_post(*args)
    post_source.call(*args).tap do |p|
      p.blog = self
    end
  end

  def entries
    @entries.sort_by{|e| e.pubdate}.reverse.take(10)
  end

  def add_entry(entry)
    @entries << entry
  end

  private

  def post_source
    # public_method inistatiates a callable Method object
    # When the objects #call method is invoked it will be
    # as if we called the named method on the original object
    # public_method respects public/private boundaries and will
    # generate a Method object for a private method
    @post_source ||= Post.public_method(:new)
  end
end

app/models/post.rb
class Post
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  extend ActiveModel::Naming


  attr_accessor :blog, :title, :body, :pubdate, :image_url

  validates :title, presence: true

  def initialize(attrs={})
    attrs.each do |k, v| send("#{k}=", v) end
  end

  def publish(clock=DateTime)
    return false unless valid?

    self.pubdate = clock.now
    blog.add_entry(self)
  end

  def persisted?
    false
  end

  def picture?
    image_url.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :init_blog

  helper :exhibits

  private

  def init_blog
    @blog = THE_BLOG
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = @blog.new_post
  end

  def create
    @post = @blog.new_post(params[:post])
    if @post.publish
      redirect_to root_path, notice: 'Post Added'
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
  def exhibit(model,context)
    Exhibit.exhibit(model, context)
  end
end

app/views/blog/_entry.html.erb
<% entry = exhibit(entry, self) %>

<article>
  <header>
    <p>
      <time>
        <%= entry.pubdate %>
      </time>
    </p>
    <h3><%= entry.title %></h3>
  </header>
  <p>
    <%= entry.render_body %>
  </p>
</article>

app/views/blog/index.html.erb
<h1><%= @blog.title %></h1>
<h2><%= @blog.subtitle %></h2>

<%= render partial: 'entry', collection: @blog.entries %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="sidebar two columns">
    <nav>
      <ul>
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
      </ul>
    </nav>
  </div>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_picture_body.html.erb
<figure>
  <img src="<%= post.image_url %>" />
  <figcaption>
    <%= post.body %>
  </figcaption>
</figure>

app/views/posts/_text_body.html.erb
<figure>
  <figcaption>
    <%= post.body %>
  </figcaption>
</figure>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> encountered, please check your input.</h2>

        <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
  <% end %>
 <div>
    <%= f.text_field :title %>
 </div>
 <div>
    <%= f.text_area :body %>
 </div>
 <div>
   <%= label :image_url, "Picture Url" %>
   <%= f.text_field :image_url %>
 </div>

  <%= f.submit %>
<% end %>